#!/bin/bash
export PATH=INSTALLPREFIX/openmpi-OPENMPIEXACTVERSION/bin:$PATH
export LD_LIBRARY_PATH=INSTALLPREFIX/openmpi-OPENMPIEXACTVERSION/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=INSTALLPREFIX/openmpi-OPENMPIEXACTVERSION/lib/pkgconfig:$PKG_CONFIG_PATH
export MANPATH=INSTALLPREFIX/openmpi-OPENMPIEXACTVERSION/share/man:$MANPATH
export MPI_BIN=INSTALLPREFIX/openmpi-OPENMPIEXACTVERSION/bin
export MPI_SYSCONFIG=INSTALLPREFIX/openmpi-OPENMPIEXACTVERSION/etc
export MPI_FORTRAN_MOD_DIR=INSTALLPREFIX/openmpi-OPENMPIEXACTVERSION/lib
export MPI_INCLUDE=INSTALLPREFIX/openmpi-OPENMPIEXACTVERSION/include
export MPI_LIB=INSTALLPREFIX/openmpi-OPENMPIEXACTVERSION/lib
export MPI_MAN=INSTALLPREFIX/openmpi-OPENMPIEXACTVERSION/share/man
export MPI_HOME=INSTALLPREFIX/openmpi-OPENMPIEXACTVERSION