#!/bin/bash
export PATH=INSTALLPREFIX/openmpi-OPENMPIVERSION/bin:$PATH
export LD_LIBRARY_PATH=INSTALLPREFIX/openmpi-OPENMPIVERSION/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=INSTALLPREFIX/openmpi-OPENMPIVERSION/lib/pkgconfig:$PKG_CONFIG_PATH
export MANPATH=INSTALLPREFIX/openmpi-OPENMPIVERSION/share/man:$MANPATH
export MPI_BIN=INSTALLPREFIX/openmpi-OPENMPIVERSION/bin
export MPI_SYSCONFIG=INSTALLPREFIX/openmpi-OPENMPIVERSION/etc
export MPI_FORTRAN_MOD_DIR=INSTALLPREFIX/openmpi-OPENMPIVERSION/lib
export MPI_INCLUDE=INSTALLPREFIX/openmpi-OPENMPIVERSION/include
export MPI_LIB=INSTALLPREFIX/openmpi-OPENMPIVERSION/lib
export MPI_MAN=INSTALLPREFIX/openmpi-OPENMPIVERSION/share/man
export MPI_HOME=INSTALLPREFIX/openmpi-OPENMPIVERSION